<a href="https://colab.research.google.com/github/ARKESH2004/ML-MATH/blob/main/MLvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [8]:
print(v+w)

[3 4 4]


In [9]:
print(v-w)

[-1 -6  0]


In [10]:
#sclr mult
print(3*v)

[ 3 -3  6]


In [16]:
print(np.linalg.norm(v))

2.449489742783178


In [17]:
s = np.dot(v,w)
print(s)

1
